namespace ClimateProject.Application.Surveys;

// ---------------------------------------------------------------------------
// THE RESPONDENT SURFACE (#118)
//
// Same #195 rule as SurveyDtos.cs and for the same reason: not one property below is
// En/Es-shaped. Content arrives already resolved, with ResolvedLocale naming the
// language the text is ACTUALLY in -- a Spanish-only survey opened with ?lang=en comes
// back in Spanish and says so.
// ---------------------------------------------------------------------------

/// <summary>
/// One answer as the respondent submits it.
/// </summary>
/// <param name="Value">
/// The single answer. For a choice or scale question this is the option's stable,
/// locale-independent <c>Value</c> -- the string
/// <c>SurveyQuestionOptionDto.Value</c> handed out by the respond payload, never the
/// label the respondent read. For an open-ended question it is the text they typed.
/// </param>
/// <param name="Values">The ordered option values, for a ranking question only.</param>
/// <param name="Text">An optional free-text comment. Rejected on an open-ended question, whose answer is already text.</param>
public sealed record SurveyAnswerInput(
    Guid QuestionId,
    string? Value = null,
    IReadOnlyList<string>? Values = null,
    string? Text = null,
    int? TimeSpentSeconds = null);

/// <param name="SessionId">
/// The idempotency key, and the resume key. Generated by the client and kept stable
/// across a retry and across a reopened tab.
///
/// Required on an anonymous survey, where it is the only thing that can tell a retried
/// request from a second respondent. Optional on an identified one, where the acting
/// user is the stronger key -- a retry that lost its session id still cannot duplicate.
/// </param>
/// <param name="IsComplete">
/// False saves progress and leaves the response open; true finishes it. A partial save
/// is refused when the survey sets <c>AllowPartialResponses = false</c>.
/// </param>
/// <param name="Language">
/// The locale the respondent actually answered in ('en' | 'es'). Recorded on the
/// response rather than inferred later: <c>Response.Language</c> exists because the
/// live word cloud counted "trabajo" and "work" as unrelated entries with nothing
/// anywhere recording which language a respondent had been reading.
/// </param>
public sealed record SubmitSurveyResponseRequest(
    IReadOnlyList<SurveyAnswerInput>? Answers = null,
    string? SessionId = null,
    bool IsComplete = true,
    string? Language = null,
    int? TotalTimeSeconds = null);

/// <param name="Value">Set for a single-valued answer.</param>
/// <param name="Values">Set for a ranking answer.</param>
public sealed record SurveySavedAnswerDto(
    Guid QuestionId,
    string? Value,
    IReadOnlyList<string>? Values,
    string? Text,
    int? TimeSpentSeconds);

/// <summary>
/// A response in progress, as returned by the respond payload so a closed tab can be
/// recovered. Carries no <c>UserId</c> in either mode -- an anonymous response has none,
/// and an identified one is being read by the person it belongs to.
/// </summary>
public sealed record SurveyResponseState(
    Guid ResponseId,
    string SessionId,
    bool IsComplete,
    string Language,
    DateTimeOffset StartTime,
    DateTimeOffset? CompletionTime,
    IReadOnlyList<SurveySavedAnswerDto> Answers);

/// <summary>
/// The survey as a respondent sees it: enough to render and answer, and nothing else.
/// Deliberately not <c>SurveyDetail</c> -- that carries CreatedBy, ResponseCount, the
/// notification settings and the allowed status transitions, none of which are a
/// respondent's business and one of which (this survey is anonymous and has had 3
/// responses) is actively harmful to hand to the person about to be the fourth.
/// </summary>
/// <param name="AutoSave">
/// <c>Survey.Settings.AutoSave</c>, served so the respond form can honour it (#369).
///
/// It was the one setting on this page the client could not see. Every other flag that
/// shapes the form -- ShowProgress, AllowPartialResponses, RandomizeQuestions,
/// TimeLimitMinutes -- is carried here, and the form's own comment recorded AutoSave as
/// a gap rather than a decision: the setting existed on <c>SurveySettingsDto</c>, the
/// respondent's payload did not carry it, so the page could not tell a survey that
/// asked for background saving from one that did not, and offered the save BUTTON to
/// both. Autosaving without it would have been inventing behaviour for every survey
/// whose author had turned it off.
///
/// It is a second gate, never a replacement for <see cref="AllowPartialResponses"/>: a
/// survey that forbids partial responses is refused by the submit endpoint itself, so
/// background saving is impossible there whatever this says.
/// </param>
public sealed record SurveyRespondView(
    Guid Id,
    string? Title,
    string? Description,
    string Type,
    string Language,
    string ResolvedLocale,
    IReadOnlyList<string> FallbackFields,
    DateTimeOffset StartDate,
    DateTimeOffset EndDate,
    bool Anonymous,
    bool AllowPartialResponses,
    bool AutoSave,
    bool RandomizeQuestions,
    bool ShowProgress,
    int? TimeLimitMinutes,
    IReadOnlyList<SurveyQuestionDto> Questions,
    SurveyResponseState? InProgress);

/// <param name="AlreadySubmitted">
/// True when this call found a response that was already complete and therefore changed
/// nothing. It is what makes a retried submit safe: the caller gets 200 and the same
/// <see cref="ResponseId"/> rather than either a duplicate row or a 409 that a network
/// retry cannot distinguish from a real error.
/// </param>
/// <param name="SuppressedDemographics">
/// Demographic fields deliberately not recorded because the respondent's value put them
/// in a group smaller than <see cref="SurveyResponsePrivacy.MinimumCohortSize"/>.
/// Always empty for an identified response.
/// </param>
public sealed record SurveySubmissionResult(
    Guid ResponseId,
    string SessionId,
    bool IsComplete,
    bool IsAnonymous,
    bool AlreadySubmitted,
    string Language,
    int AnsweredQuestionCount,
    int QuestionCount,
    IReadOnlyList<string> SuppressedDemographics);
