// <auto-generated />
using System;
using System.Collections.Generic;
using ClimateTracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClimateTracking.Infrastructure.Migrations
{
    [DbContext(typeof(ClimateTrackingDbContext))]
    [Migration("20260729142701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClimateTracking.Domain.Entities.BitacoraEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvanceAnterior")
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("AvanceNuevo")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("PlanDeAccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlanDeAccionId");

                    b.ToTable("bitacora_entries", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.CicloEncuestaCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("FechaApertura")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroPreguntas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("ciclos_encuesta_cache", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.HallazgoCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BenchmarkSectorPct")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CicloExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodoExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("ResultadoAnioAnteriorPct")
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("ResultadoPct")
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("hallazgos_cache", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.NodoCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadColaboradores")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiderExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NodoPadreExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("nodos_cache", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.PrimitiveCollection<string[]>("Destinatarios")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanDeAccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDisparador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PlanDeAccionId");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.PersonaCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodoExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("personas_cache", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.PlanDeAccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CicloEncuestaExternalId")
                        .HasColumnType("text");

                    b.Property<bool>("Cumplido")
                        .HasColumnType("boolean");

                    b.Property<string>("DescripcionQue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EstadoSemaforo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaCompromiso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaUltimaActualizacion")
                        .HasColumnType("date");

                    b.Property<string>("HallazgoExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LiderExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetodologiaComo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NodoExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PorcentajeAvance")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("ResponsableEjecucionExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<List<string>>("_involucradosExternalIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("involucrados_external_ids");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode")
                        .IsUnique();

                    b.HasIndex("_involucradosExternalIds")
                        .HasDatabaseName("ix_planes_de_accion_involucrados");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_involucradosExternalIds"), "gin");

                    b.ToTable("planes_de_accion", (string)null);
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.SemaforoThresholdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiasAmarilloSinActualizar")
                        .HasColumnType("integer");

                    b.Property<int>("DiasAntesVencimientoAmarillo")
                        .HasColumnType("integer");

                    b.Property<int>("DiasRojoSinActualizar")
                        .HasColumnType("integer");

                    b.Property<decimal>("FraccionMitadPlazo")
                        .HasColumnType("numeric(5,4)");

                    b.PrimitiveCollection<int[]>("Hitos")
                        .HasColumnType("integer[]");

                    b.Property<string>("TipoAvanceEsperado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("semaforo_threshold_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DiasAmarilloSinActualizar = 30,
                            DiasAntesVencimientoAmarillo = 30,
                            DiasRojoSinActualizar = 60,
                            FraccionMitadPlazo = 0.5m,
                            TipoAvanceEsperado = "Continuo"
                        });
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.BitacoraEntry", b =>
                {
                    b.HasOne("ClimateTracking.Domain.Entities.PlanDeAccion", null)
                        .WithMany("_bitacora")
                        .HasForeignKey("PlanDeAccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("ClimateTracking.Domain.Entities.PlanDeAccion", null)
                        .WithMany()
                        .HasForeignKey("PlanDeAccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClimateTracking.Domain.Entities.PlanDeAccion", b =>
                {
                    b.Navigation("_bitacora");
                });
#pragma warning restore 612, 618
        }
    }
}
