using Microsoft.EntityFrameworkCore.Migrations;
using NpgsqlTypes;

#nullable disable

namespace ClimateProject.Infrastructure.Migrations
{
    /// <summary>
    /// The full-text search index behind global search (#145): one stored generated
    /// <c>search_vector</c> column and one GIN index on each of the six searchable tables.
    ///
    /// See <c>SearchIndexConfiguration</c> for why the vector is built with the
    /// <c>simple</c> text-search configuration rather than <c>english</c>/<c>spanish</c>,
    /// and why it is a generated column rather than a trigger.
    ///
    /// Deployment note. <c>ADD COLUMN ... GENERATED ALWAYS AS (...) STORED</c> rewrites the
    /// table under an ACCESS EXCLUSIVE lock, and <c>CREATE INDEX</c> here is not
    /// CONCURRENTLY -- EF migrations run inside a transaction and CONCURRENTLY cannot. On
    /// today's data (production is empty; the ETL in #154 has not run) that is instant. If
    /// this ships after a large import instead, build the six indexes by hand with
    /// CREATE INDEX CONCURRENTLY first; the migration's CreateIndex then finds them
    /// already present only if the names match exactly, so prefer scheduling the window.
    ///
    /// Down is a clean reversal: the columns are derived, so dropping them loses nothing
    /// that cannot be regenerated by re-applying Up.
    /// </summary>
    public partial class AddSearchVectors : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "users",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(email, '') || ' ' || translate(coalesce(email, ''), '@._-', '    '))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "surveys",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title_en, '') || ' ' || coalesce(title_es, '') || ' ' || coalesce(description_en, '') || ' ' || coalesce(description_es, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "reports",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "questions",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(text_en, '') || ' ' || coalesce(text_es, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "departments",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "action_plans",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.CreateIndex(
                name: "IX_users_search_vector",
                table: "users",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_surveys_search_vector",
                table: "surveys",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_reports_search_vector",
                table: "reports",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_questions_search_vector",
                table: "questions",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_departments_search_vector",
                table: "departments",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_action_plans_search_vector",
                table: "action_plans",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_users_search_vector",
                table: "users");

            migrationBuilder.DropIndex(
                name: "IX_surveys_search_vector",
                table: "surveys");

            migrationBuilder.DropIndex(
                name: "IX_reports_search_vector",
                table: "reports");

            migrationBuilder.DropIndex(
                name: "IX_questions_search_vector",
                table: "questions");

            migrationBuilder.DropIndex(
                name: "IX_departments_search_vector",
                table: "departments");

            migrationBuilder.DropIndex(
                name: "IX_action_plans_search_vector",
                table: "action_plans");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "users");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "surveys");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "reports");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "questions");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "departments");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "action_plans");
        }
    }
}
