using Microsoft.EntityFrameworkCore.Migrations;
using NpgsqlTypes;

#nullable disable

namespace ClimateProject.Infrastructure.Migrations
{
    /// <summary>
    /// The full-text search index behind global search (#145): one stored generated
    /// <c>search_vector</c> column and one GIN index on each of the six searchable tables.
    ///
    /// See <c>SearchIndexConfiguration</c> for why the vector is built with the
    /// <c>simple</c> text-search configuration rather than <c>english</c>/<c>spanish</c>,
    /// and why it is a generated column rather than a trigger.
    ///
    /// Deployment note. This migration takes an ACCESS EXCLUSIVE lock on all six tables and
    /// holds it for the whole thing: <c>ADD COLUMN ... GENERATED ALWAYS AS (...) STORED</c>
    /// rewrites each table, and the <c>CREATE INDEX</c> calls that follow are not
    /// CONCURRENTLY, because EF runs a migration inside one transaction and CONCURRENTLY
    /// cannot run in one. On today's data (production is empty; the ETL in #154 has not run)
    /// that is instant.
    ///
    /// There is no way to pre-build these indexes to shorten that window, and the obvious
    /// attempt makes things worse. Verified against <c>dotnet ef migrations script</c>:
    ///
    /// <list type="bullet">
    /// <item>The <c>ALTER TABLE ... ADD search_vector</c> statements are emitted *before*
    /// every <c>CREATE INDEX</c>, and the column exists nowhere else. Until this migration
    /// runs there is nothing to index, so a CONCURRENTLY build cannot be done ahead of it.</item>
    /// <item>The emitted DDL is a bare <c>CREATE INDEX "IX_users_search_vector" ON users
    /// USING gin (search_vector);</c> -- no <c>IF NOT EXISTS</c>. An index already carrying
    /// that name therefore aborts the statement, and since the whole migration is one
    /// transaction, the six ALTER TABLEs roll back with it. "Already present" is a failure
    /// here, not a shortcut.</item>
    /// </list>
    ///
    /// If this ever ships onto a large table, the answer is a maintenance window, or a
    /// hand-written migration that splits the column add from the index build across two
    /// migrations with <c>SuppressTransaction</c> on the second. Do not hand-build indexes
    /// under these names beforehand.
    ///
    /// Down is a clean reversal: the columns are derived, so dropping them loses nothing
    /// that cannot be regenerated by re-applying Up.
    /// </summary>
    public partial class AddSearchVectors : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "users",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(email, '') || ' ' || translate(coalesce(email, ''), '@._-', '    '))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "surveys",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title_en, '') || ' ' || coalesce(title_es, '') || ' ' || coalesce(description_en, '') || ' ' || coalesce(description_es, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "reports",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "questions",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(text_en, '') || ' ' || coalesce(text_es, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "departments",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.AddColumn<NpgsqlTsVector>(
                name: "search_vector",
                table: "action_plans",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))",
                stored: true);

            migrationBuilder.CreateIndex(
                name: "IX_users_search_vector",
                table: "users",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_surveys_search_vector",
                table: "surveys",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_reports_search_vector",
                table: "reports",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_questions_search_vector",
                table: "questions",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_departments_search_vector",
                table: "departments",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "IX_action_plans_search_vector",
                table: "action_plans",
                column: "search_vector")
                .Annotation("Npgsql:IndexMethod", "gin");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_users_search_vector",
                table: "users");

            migrationBuilder.DropIndex(
                name: "IX_surveys_search_vector",
                table: "surveys");

            migrationBuilder.DropIndex(
                name: "IX_reports_search_vector",
                table: "reports");

            migrationBuilder.DropIndex(
                name: "IX_questions_search_vector",
                table: "questions");

            migrationBuilder.DropIndex(
                name: "IX_departments_search_vector",
                table: "departments");

            migrationBuilder.DropIndex(
                name: "IX_action_plans_search_vector",
                table: "action_plans");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "users");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "surveys");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "reports");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "questions");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "departments");

            migrationBuilder.DropColumn(
                name: "search_vector",
                table: "action_plans");
        }
    }
}
